# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/psyche-hmscore/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),psyche-hmscore)

endif
