# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/psyche-hmscore/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/psyche-hmscore

PRODUCT_COPY_FILES += \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib/libaegissec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaegissec.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib/libapms_ndk_anr.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libapms_ndk_anr.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib/libapppatch.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libapppatch.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib/libdex2oat-util.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdex2oat-util.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib/libfb.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libfb.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib/libgifimage.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libgifimage.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib/libhilog.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libhilog.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib/libimagepipeline.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libimagepipeline.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib/libjslite.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libjslite.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib/libnative-filters.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libnative-filters.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib/libnative-imagetranscoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libnative-imagetranscoder.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib/libnllvm-base.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libnllvm-base.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib/libscannative.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libscannative.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib/libstatic-webp.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstatic-webp.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib/libyoga.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libyoga.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib64/libaegissec.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaegissec.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib64/libapms_ndk_anr.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libapms_ndk_anr.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib64/libapppatch.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libapppatch.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib64/libdex2oat-util.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libdex2oat-util.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib64/libfb.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libfb.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib64/libgifimage.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libgifimage.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib64/libhilog.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libhilog.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib64/libimagepipeline.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libimagepipeline.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib64/libjslite.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjslite.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib64/libnative-filters.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libnative-filters.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib64/libnative-imagetranscoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libnative-imagetranscoder.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib64/libnllvm-base.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libnllvm-base.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib64/libscannative.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libscannative.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib64/libstatic-webp.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libstatic-webp.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/lib64/libyoga.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libyoga.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/priv-app/com.huawei.appmarket/lib/arm64/libaegissec.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/com.huawei.appmarket/lib/arm64/libaegissec.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/priv-app/com.huawei.appmarket/lib/arm64/libapms_ndk_anr.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/com.huawei.appmarket/lib/arm64/libapms_ndk_anr.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/priv-app/com.huawei.appmarket/lib/arm64/libapppatch.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/com.huawei.appmarket/lib/arm64/libapppatch.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/priv-app/com.huawei.appmarket/lib/arm64/libfb.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/com.huawei.appmarket/lib/arm64/libfb.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/priv-app/com.huawei.appmarket/lib/arm64/libgifimage.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/com.huawei.appmarket/lib/arm64/libgifimage.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/priv-app/com.huawei.appmarket/lib/arm64/libhilog.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/com.huawei.appmarket/lib/arm64/libhilog.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/priv-app/com.huawei.appmarket/lib/arm64/libimagepipeline.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/com.huawei.appmarket/lib/arm64/libimagepipeline.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/priv-app/com.huawei.appmarket/lib/arm64/libjslite.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/com.huawei.appmarket/lib/arm64/libjslite.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/priv-app/com.huawei.appmarket/lib/arm64/libnative-filters.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/com.huawei.appmarket/lib/arm64/libnative-filters.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/priv-app/com.huawei.appmarket/lib/arm64/libnative-imagetranscoder.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/com.huawei.appmarket/lib/arm64/libnative-imagetranscoder.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/priv-app/com.huawei.appmarket/lib/arm64/libscannative.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/com.huawei.appmarket/lib/arm64/libscannative.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/priv-app/com.huawei.appmarket/lib/arm64/libstatic-webp.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/com.huawei.appmarket/lib/arm64/libstatic-webp.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/priv-app/com.huawei.appmarket/lib/arm64/libyoga.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/com.huawei.appmarket/lib/arm64/libyoga.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/priv-app/com.huawei.appmarket/oat/arm64/base.odex:$(TARGET_COPY_OUT_SYSTEM)/priv-app/com.huawei.appmarket/oat/arm64/base.odex \
    vendor/xiaomi/psyche-hmscore/proprietary/system/priv-app/com.huawei.appmarket/oat/arm64/base.vdex:$(TARGET_COPY_OUT_SYSTEM)/priv-app/com.huawei.appmarket/oat/arm64/base.vdex \
    vendor/xiaomi/psyche-hmscore/proprietary/system/app/com.huawei.hwid/lib/arm64/libaegissec.so:$(TARGET_COPY_OUT_SYSTEM)/app/com.huawei.hwid/lib/arm64/libaegissec.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/app/com.huawei.hwid/lib/arm64/libdex2oat-util.so:$(TARGET_COPY_OUT_SYSTEM)/app/com.huawei.hwid/lib/arm64/libdex2oat-util.so \
    vendor/xiaomi/psyche-hmscore/proprietary/system/app/com.huawei.hwid/oat/arm64/base.odex:$(TARGET_COPY_OUT_SYSTEM)/app/com.huawei.hwid/oat/arm64/base.odex \
    vendor/xiaomi/psyche-hmscore/proprietary/system/app/com.huawei.hwid/oat/arm64/base.vdex:$(TARGET_COPY_OUT_SYSTEM)/app/com.huawei.hwid/oat/arm64/base.vdex

PRODUCT_PACKAGES += \
    com.huawei.hwid \
    com.huawei.appmarket
